version: '3.8'
services:
  np11app:
    container_name: np11app
    build: .
    volumes:
      - ./www:/www
    env_file: 
      - .env
    ports:
      - 5000:5000
    expose:
      - 5000
    working_dir: /www
    command: flask run
